name: Render Paper
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  render-paper:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [thesis, assignment]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: templates/${{ matrix.type }}/template/lib.typ

      - name: Install Fontist
        uses: fontist/setup-fontist@v2

      - name: Install Fonts
        run: fontist install "Fira Code" && fontist install "TeX" && sudo apt-get install -y fonts-texgyre

      - name: Read version from typst.toml
        uses: SebRollen/toml-action@v1.2.0
        id: read_toml
        with:
          file: 'templates/${{ matrix.type }}/typst.toml'
          field: 'package.version'

      - name: Replace preview with local names in example
        run: |
          file_path="path/to/your/file.txt"
          sed -i "" -e 's/preview/local/g' "templates/${{ matrix.type }}/example/main.typ"

      - name: Create target directory
        run: mkdir -p ~/.local/share/typst/packages/local/modern-whs-${{ matrix.type }}/${{ steps.read_toml.outputs.value}}

      - name: Copy package to data directory
        run: cp -r templates/${{ matrix.type }}/. ~/.local/share/typst/packages/local/modern-whs-${{ matrix.type }}/${{ steps.read_toml.outputs.value}}/

      - name: Render Paper
        run: typst compile templates/${{ matrix.type }}/example/main.typ ${{ matrix.type }}.pdf --font-path ~/.fontist/fonts

      - name: Upload Paper
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }}
          path: ${{ matrix.type }}.pdf