name: Render Paper
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  render-paper:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [thesis]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: templates/${{ matrix.type }}/template/lib.typ

      - name: Install Fontist
        uses: fontist/setup-fontist@v2

      - name: Install Fonts
        run: fontist install "Fira Code" && fontist install "TeX" && sudo apt-get install -y fonts-texgyre

      - name: Create target directory
        run: mkdir -p ~/.local/share/typst/packages/local/whs-${{ matrix.type }}/0.1.0

      - name: Copy package to data directory
        run: cp -r templates/${{ matrix.type }}/. ~/.local/share/typst/packages/local/whs-${{ matrix.type }}/0.1.0/

      - name: Render Paper
        run: typst compile templates/${{ matrix.type }}/example/main.typ ${{ matrix.type }}.pdf --font-path ~/.fontist/fonts

      - name: Upload Paper
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type }}
          path: ${{ matrix.type }}.pdf